
Event.destroy_all
User.destroy_all
Attendee.destroy_all

Event.create(id: 1, title: 'Javascript and the browser', max_tix: 50, date_time: Time.zone.local(2015,05,22,9,0,0), description: "Learn the 1 special trick that Front End Developers don't want you to know!")
Event.create(id: 2, title: 'The Back end', max_tix: 50, date_time: Time.zone.local(2015,05,22,9,30,0), description: "The dark side of programming is a scary place... ")
Event.create(id: 3, title: 'The Front end', max_tix: 50, date_time: Time.zone.local(2015,05,22,10,00,0), description: "The light side of programming is a scary place... ")
Event.create(id: 4, title: 'Ruby World', max_tix: 50, date_time: Time.zone.local(2015,05,22,10,30,0), description: "Rubies will be the new diamond in the rough! ")
Event.create(id: 5, title: 'Ruby on Rails', max_tix: 50, date_time: Time.zone.local(2015,05,22,11,00,0), description: "Rails; the way forward..... ")
Event.create(id: 6, title: 'Node - The Full Story', max_tix: 50, date_time: Time.zone.local(2015,05,22,11,30,0), description: "Node; the undervalued code.... ")
Event.create(id: 7, title: 'Underscore in the Underworld', max_tix: 50, date_time: Time.zone.local(2015,05,22,13,00,0), description: "Coming out from downunder... ")
Event.create(id: 8, title: 'jQuery - Full Story', max_tix: 50, date_time: Time.zone.local(2015,05,22,13,30,0), description: "jQuery; the way it should be... ")
Event.create(id: 9, title: 'General Assembly', max_tix: 50, date_time: Time.zone.local(2015,05,22,14,00,0), description: "Taking the world by storm as the most innovative institution! ")
Event.create(id: 10, title: 'PHP vs Javascript', max_tix: 50, date_time: Time.zone.local(2015,05,22,14,30,0), description: "The final decision is made... ")
Event.create(id: 11, title: 'CSS is Cool', max_tix: 50, date_time: Time.zone.local(2015,05,22,15,00,0), description: "Decorate the world of WWW using the coolest code... ")
Event.create(id: 12, title: 'HTML - Cold Facts', max_tix: 50, date_time: Time.zone.local(2015,05,22,15,30,0), description: "Leading the way again, WWW Flagship... ")
Event.create(id: 13, title: 'SASS', max_tix: 50, date_time: Time.zone.local(2015,05,22,16,00,0), description: "Nothing more to say but SASS it up! ")
Event.create(id: 14, title: 'Which Code For You?', max_tix: 50, date_time: Time.zone.local(2015,05,22,16,30,0), description: "Like clothes and cars, which code is best for you?... ")
Event.create(id: 15, title: 'TDD 4U', max_tix: 50, date_time: Time.zone.local(2015,05,22,17,00,0), description: "The untold story of TDD... ")
Event.create(id: 16, title: 'The Web Developers Friend', max_tix: 50, date_time: Time.zone.local(2015,05,22,17,30,0), description: "Software must-haves for up and coming developers... ")


User.create(id: 1, name: 'Matt Cameron', email: 'mattlbcameron@gmail.com', password: 'password', bio: "Matt is a legend.", admin: false)
User.create(id: 2, name: 'Dom White', email: 'domwhite@gmail.com', password: 'password', bio: "Dom is very knowledgeable about chemicals and firearms - basically, don't mess with him...", admin: false)
User.create(id: 3, name: 'Mike Goodwin', email: 'mike@gmail.com', password: 'password', bio: "Mike is reknowned for his knowledge of Javascript, the browser, and kittens", admin: false)
User.create(id: 4, name: 'Jeff Wolff', email: 'jeff@gmail.com', password: 'password', bio: "Jeff is an up and coming developer in the Ruby world.", admin: false)
User.create(id: 5, name: 'Luke Shillabeer', email: 'luke@gmail.com', password: 'password', bio: "Man of many talents, shares his knowledge.", admin: false)
User.create(id: 6, name: 'Justin Ward', email: 'justin@gmail.com', password: 'password', bio: "The man with the diamond touch when it comes to the coding world", admin: false)
User.create(id: 7, name: 'Nick Pateman', email: 'nick@gmail.com', password: 'password', bio: "With his teaching background and skills in code, get ready to learn", admin: false)
User.create(id: 8, name: 'Aden Margheriti', email: 'aden@gmail.com', password: 'password', bio: "Known as the interior decorator of the cyber world.", admin: false)
User.create(id: 9, name: 'Jaya Wijono', email: 'jaya@gmail.com', password: 'password', bio: "If there is ever a man of the security coe world its Jaya, he shares.....", admin: false)
User.create(id: 10, name: 'Beta Ngadiman', email: 'beta@gmail.com', password: 'password', bio: "The Art of Code writer, imparts his wisdom", admin: false)
User.create(id: 11, name: 'Phillip Castiglione', email: 'phil@gmail.com', password: 'password', bio: "Master of the codes and is now ready for his own unicorn code", admin: false)
User.create(id: 12, name: "Jarod O'loughlan", email: 'jarod@gmail.com', password: 'password', bio: "Jarod is renowned developer in the Node world", admin: false)
User.create(id: 13, name: 'JC Lee', email: 'jc@gmail.com', password: 'password', bio: "Fresh from the UN, JC shares her knowledge of code in Europe", admin: false)
User.create(id: 14, name: 'Louis Moore', email: 'louis@gmail.com', password: 'password', bio: "Enigmatic coder of Javascript, shows how its done.", admin: false)
User.create(id: 15, name: 'Daniel Tsui', email: 'daniel@gmail.com', password: 'password', bio: "Master of the dark codes, the wizard shines his light", admin: false)
User.create(id: 16, name: 'Matt Swann', email: 'matt@gmail.com', password: 'password', bio: "Matt is a developer in residence at General Assembly", admin: false)
User.create(id: 17, name: 'Admin', email: 'admin@admin.com', password: 'admin', admin: true)

Attendee.create(user_id: 1, event_id: 1, role: 'speaker')
Attendee.create(user_id: 2, event_id: 1, role: 'user')
Attendee.create(user_id: 3, event_id: 1, role: 'user')
Attendee.create(user_id: 4, event_id: 1, role: 'user')
Attendee.create(user_id: 5, event_id: 1, role: 'user')
Attendee.create(user_id: 6, event_id: 1, role: 'user')
Attendee.create(user_id: 7, event_id: 1, role: 'user')
Attendee.create(user_id: 8, event_id: 1, role: 'user')
Attendee.create(user_id: 9, event_id: 1, role: 'user')
Attendee.create(user_id: 10, event_id: 1, role: 'user')
Attendee.create(user_id: 11, event_id: 1, role: 'user')
Attendee.create(user_id: 12, event_id: 1, role: 'user')
Attendee.create(user_id: 13, event_id: 1, role: 'user')
Attendee.create(user_id: 14, event_id: 1, role: 'user')
Attendee.create(user_id: 15, event_id: 1, role: 'user')
Attendee.create(user_id: 16, event_id: 1, role: 'user')
Attendee.create(user_id: 1, event_id: 2, role: 'user')
Attendee.create(user_id: 2, event_id: 2, role: 'speaker')
Attendee.create(user_id: 3, event_id: 2, role: 'user')
Attendee.create(user_id: 4, event_id: 2, role: 'user')
Attendee.create(user_id: 5, event_id: 2, role: 'user')
Attendee.create(user_id: 6, event_id: 2, role: 'user')
Attendee.create(user_id: 7, event_id: 2, role: 'user')
Attendee.create(user_id: 8, event_id: 2, role: 'user')
Attendee.create(user_id: 9, event_id: 2, role: 'user')
Attendee.create(user_id: 10, event_id: 2, role: 'user')
Attendee.create(user_id: 11, event_id: 2, role: 'user')
Attendee.create(user_id: 12, event_id: 2, role: 'user')
Attendee.create(user_id: 13, event_id: 2, role: 'user')
Attendee.create(user_id: 14, event_id: 2, role: 'user')
Attendee.create(user_id: 15, event_id: 2, role: 'user')
Attendee.create(user_id: 16, event_id: 2, role: 'user')
Attendee.create(user_id: 1, event_id: 3, role: 'user')
Attendee.create(user_id: 2, event_id: 3, role: 'user')
Attendee.create(user_id: 3, event_id: 3, role: 'speaker')
Attendee.create(user_id: 4, event_id: 3, role: 'user')
Attendee.create(user_id: 5, event_id: 3, role: 'user')
Attendee.create(user_id: 6, event_id: 3, role: 'user')
Attendee.create(user_id: 7, event_id: 3, role: 'user')
Attendee.create(user_id: 8, event_id: 3, role: 'user')
Attendee.create(user_id: 9, event_id: 3, role: 'user')
Attendee.create(user_id: 10, event_id: 3, role: 'user')
Attendee.create(user_id: 11, event_id: 3, role: 'user')
Attendee.create(user_id: 12, event_id: 3, role: 'user')
Attendee.create(user_id: 13, event_id: 3, role: 'user')
Attendee.create(user_id: 14, event_id: 3, role: 'user')
Attendee.create(user_id: 15, event_id: 3, role: 'user')
Attendee.create(user_id: 16, event_id: 3, role: 'user')
Attendee.create(user_id: 1, event_id: 4, role: 'user')
Attendee.create(user_id: 2, event_id: 4, role: 'user')
Attendee.create(user_id: 3, event_id: 4, role: 'user')
Attendee.create(user_id: 4, event_id: 4, role: 'speaker')
Attendee.create(user_id: 5, event_id: 4, role: 'user')
Attendee.create(user_id: 6, event_id: 4, role: 'user')
Attendee.create(user_id: 7, event_id: 4, role: 'user')
Attendee.create(user_id: 8, event_id: 4, role: 'user')
Attendee.create(user_id: 9, event_id: 4, role: 'user')
Attendee.create(user_id: 10, event_id: 4, role: 'user')
Attendee.create(user_id: 11, event_id: 4, role: 'user')
Attendee.create(user_id: 12, event_id: 4, role: 'user')
Attendee.create(user_id: 13, event_id: 4, role: 'user')
Attendee.create(user_id: 14, event_id: 4, role: 'user')
Attendee.create(user_id: 15, event_id: 4, role: 'user')
Attendee.create(user_id: 16, event_id: 4, role: 'user')
Attendee.create(user_id: 1, event_id: 5, role: 'user')
Attendee.create(user_id: 2, event_id: 5, role: 'user')
Attendee.create(user_id: 3, event_id: 5, role: 'user')
Attendee.create(user_id: 4, event_id: 5, role: 'user')
Attendee.create(user_id: 5, event_id: 5, role: 'speaker')
Attendee.create(user_id: 6, event_id: 5, role: 'user')
Attendee.create(user_id: 7, event_id: 5, role: 'user')
Attendee.create(user_id: 8, event_id: 5, role: 'user')
Attendee.create(user_id: 9, event_id: 5, role: 'user')
Attendee.create(user_id: 10, event_id: 5, role: 'user')
Attendee.create(user_id: 11, event_id: 5, role: 'user')
Attendee.create(user_id: 12, event_id: 5, role: 'user')
Attendee.create(user_id: 13, event_id: 5, role: 'user')
Attendee.create(user_id: 14, event_id: 5, role: 'user')
Attendee.create(user_id: 15, event_id: 5, role: 'user')
Attendee.create(user_id: 16, event_id: 5, role: 'user')
Attendee.create(user_id: 1, event_id: 6, role: 'user')
Attendee.create(user_id: 2, event_id: 6, role: 'user')
Attendee.create(user_id: 3, event_id: 6, role: 'user')
Attendee.create(user_id: 4, event_id: 6, role: 'user')
Attendee.create(user_id: 5, event_id: 6, role: 'user')
Attendee.create(user_id: 6, event_id: 6, role: 'speaker')
Attendee.create(user_id: 7, event_id: 6, role: 'user')
Attendee.create(user_id: 8, event_id: 6, role: 'user')
Attendee.create(user_id: 9, event_id: 6, role: 'user')
Attendee.create(user_id: 10, event_id: 6, role: 'user')
Attendee.create(user_id: 11, event_id: 6, role: 'user')
Attendee.create(user_id: 12, event_id: 6, role: 'user')
Attendee.create(user_id: 13, event_id: 6, role: 'user')
Attendee.create(user_id: 14, event_id: 6, role: 'user')
Attendee.create(user_id: 15, event_id: 6, role: 'user')
Attendee.create(user_id: 16, event_id: 6, role: 'user')
Attendee.create(user_id: 1, event_id: 7, role: 'user')
Attendee.create(user_id: 2, event_id: 7, role: 'user')
Attendee.create(user_id: 3, event_id: 7, role: 'user')
Attendee.create(user_id: 4, event_id: 7, role: 'user')
Attendee.create(user_id: 5, event_id: 7, role: 'user')
Attendee.create(user_id: 6, event_id: 7, role: 'user')
Attendee.create(user_id: 7, event_id: 7, role: 'speaker')
Attendee.create(user_id: 8, event_id: 7, role: 'user')
Attendee.create(user_id: 9, event_id: 7, role: 'user')
Attendee.create(user_id: 10, event_id: 7, role: 'user')
Attendee.create(user_id: 11, event_id: 7, role: 'user')
Attendee.create(user_id: 12, event_id: 7, role: 'user')
Attendee.create(user_id: 13, event_id: 7, role: 'user')
Attendee.create(user_id: 14, event_id: 7, role: 'user')
Attendee.create(user_id: 15, event_id: 7, role: 'user')
Attendee.create(user_id: 16, event_id: 7, role: 'user')
Attendee.create(user_id: 1, event_id: 8, role: 'user')
Attendee.create(user_id: 2, event_id: 8, role: 'user')
Attendee.create(user_id: 3, event_id: 8, role: 'user')
Attendee.create(user_id: 4, event_id: 8, role: 'user')
Attendee.create(user_id: 5, event_id: 8, role: 'user')
Attendee.create(user_id: 6, event_id: 8, role: 'user')
Attendee.create(user_id: 7, event_id: 8, role: 'user')
Attendee.create(user_id: 8, event_id: 8, role: 'speaker')
Attendee.create(user_id: 9, event_id: 8, role: 'user')
Attendee.create(user_id: 10, event_id: 8, role: 'user')
Attendee.create(user_id: 11, event_id: 8, role: 'user')
Attendee.create(user_id: 12, event_id: 8, role: 'user')
Attendee.create(user_id: 13, event_id: 8, role: 'user')
Attendee.create(user_id: 14, event_id: 8, role: 'user')
Attendee.create(user_id: 15, event_id: 8, role: 'user')
Attendee.create(user_id: 16, event_id: 8, role: 'user')
Attendee.create(user_id: 1, event_id: 9, role: 'user')
Attendee.create(user_id: 2, event_id: 9, role: 'user')
Attendee.create(user_id: 3, event_id: 9, role: 'user')
Attendee.create(user_id: 4, event_id: 9, role: 'user')
Attendee.create(user_id: 5, event_id: 9, role: 'user')
Attendee.create(user_id: 6, event_id: 9, role: 'user')
Attendee.create(user_id: 7, event_id: 9, role: 'user')
Attendee.create(user_id: 8, event_id: 9, role: 'user')
Attendee.create(user_id: 9, event_id: 9, role: 'speaker')
Attendee.create(user_id: 10, event_id: 9, role: 'user')
Attendee.create(user_id: 11, event_id: 9, role: 'user')
Attendee.create(user_id: 12, event_id: 9, role: 'user')
Attendee.create(user_id: 13, event_id: 9, role: 'user')
Attendee.create(user_id: 14, event_id: 9, role: 'user')
Attendee.create(user_id: 15, event_id: 9, role: 'user')
Attendee.create(user_id: 16, event_id: 9, role: 'user')
Attendee.create(user_id: 1, event_id: 10, role: 'user')
Attendee.create(user_id: 2, event_id: 10, role: 'user')
Attendee.create(user_id: 3, event_id: 10, role: 'user')
Attendee.create(user_id: 4, event_id: 10, role: 'user')
Attendee.create(user_id: 5, event_id: 10, role: 'user')
Attendee.create(user_id: 6, event_id: 10, role: 'user')
Attendee.create(user_id: 7, event_id: 10, role: 'user')
Attendee.create(user_id: 8, event_id: 10, role: 'user')
Attendee.create(user_id: 9, event_id: 10, role: 'user')
Attendee.create(user_id: 10, event_id: 10, role: 'speaker')
Attendee.create(user_id: 11, event_id: 10, role: 'user')
Attendee.create(user_id: 12, event_id: 10, role: 'user')
Attendee.create(user_id: 13, event_id: 10, role: 'user')
Attendee.create(user_id: 14, event_id: 10, role: 'user')
Attendee.create(user_id: 15, event_id: 10, role: 'user')
Attendee.create(user_id: 16, event_id: 10, role: 'user')
Attendee.create(user_id: 1, event_id: 11, role: 'user')
Attendee.create(user_id: 2, event_id: 11, role: 'user')
Attendee.create(user_id: 3, event_id: 11, role: 'user')
Attendee.create(user_id: 4, event_id: 11, role: 'user')
Attendee.create(user_id: 5, event_id: 11, role: 'user')
Attendee.create(user_id: 6, event_id: 11, role: 'user')
Attendee.create(user_id: 7, event_id: 11, role: 'user')
Attendee.create(user_id: 8, event_id: 11, role: 'user')
Attendee.create(user_id: 9, event_id: 11, role: 'user')
Attendee.create(user_id: 10, event_id: 11, role: 'user')
Attendee.create(user_id: 11, event_id: 11, role: 'speaker')
Attendee.create(user_id: 12, event_id: 11, role: 'user')
Attendee.create(user_id: 13, event_id: 11, role: 'user')
Attendee.create(user_id: 14, event_id: 11, role: 'user')
Attendee.create(user_id: 15, event_id: 11, role: 'user')
Attendee.create(user_id: 16, event_id: 11, role: 'user')
Attendee.create(user_id: 1, event_id: 12, role: 'user')
Attendee.create(user_id: 2, event_id: 12, role: 'user')
Attendee.create(user_id: 3, event_id: 12, role: 'user')
Attendee.create(user_id: 4, event_id: 12, role: 'user')
Attendee.create(user_id: 5, event_id: 12, role: 'user')
Attendee.create(user_id: 6, event_id: 12, role: 'user')
Attendee.create(user_id: 7, event_id: 12, role: 'user')
Attendee.create(user_id: 8, event_id: 12, role: 'user')
Attendee.create(user_id: 9, event_id: 12, role: 'user')
Attendee.create(user_id: 10, event_id: 12, role: 'user')
Attendee.create(user_id: 11, event_id: 12, role: 'user')
Attendee.create(user_id: 12, event_id: 12, role: 'speaker')
Attendee.create(user_id: 13, event_id: 12, role: 'user')
Attendee.create(user_id: 14, event_id: 12, role: 'user')
Attendee.create(user_id: 15, event_id: 12, role: 'user')
Attendee.create(user_id: 16, event_id: 12, role: 'user')
Attendee.create(user_id: 1, event_id: 13, role: 'user')
Attendee.create(user_id: 2, event_id: 13, role: 'user')
Attendee.create(user_id: 3, event_id: 13, role: 'user')
Attendee.create(user_id: 4, event_id: 13, role: 'user')
Attendee.create(user_id: 5, event_id: 13, role: 'user')
Attendee.create(user_id: 6, event_id: 13, role: 'user')
Attendee.create(user_id: 7, event_id: 13, role: 'user')
Attendee.create(user_id: 8, event_id: 13, role: 'user')
Attendee.create(user_id: 9, event_id: 13, role: 'user')
Attendee.create(user_id: 10, event_id: 13, role: 'user')
Attendee.create(user_id: 11, event_id: 13, role: 'user')
Attendee.create(user_id: 12, event_id: 13, role: 'user')
Attendee.create(user_id: 13, event_id: 13, role: 'speaker')
Attendee.create(user_id: 14, event_id: 13, role: 'user')
Attendee.create(user_id: 15, event_id: 13, role: 'user')
Attendee.create(user_id: 16, event_id: 13, role: 'user')
Attendee.create(user_id: 1, event_id: 14, role: 'user')
Attendee.create(user_id: 2, event_id: 14, role: 'user')
Attendee.create(user_id: 3, event_id: 14, role: 'user')
Attendee.create(user_id: 4, event_id: 14, role: 'user')
Attendee.create(user_id: 5, event_id: 14, role: 'user')
Attendee.create(user_id: 6, event_id: 14, role: 'user')
Attendee.create(user_id: 7, event_id: 14, role: 'user')
Attendee.create(user_id: 8, event_id: 14, role: 'user')
Attendee.create(user_id: 9, event_id: 14, role: 'user')
Attendee.create(user_id: 10, event_id: 14, role: 'user')
Attendee.create(user_id: 11, event_id: 14, role: 'user')
Attendee.create(user_id: 12, event_id: 14, role: 'user')
Attendee.create(user_id: 13, event_id: 14, role: 'user')
Attendee.create(user_id: 14, event_id: 14, role: 'speaker')
Attendee.create(user_id: 15, event_id: 14, role: 'user')
Attendee.create(user_id: 16, event_id: 14, role: 'user')
Attendee.create(user_id: 1, event_id: 15, role: 'user')
Attendee.create(user_id: 2, event_id: 15, role: 'user')
Attendee.create(user_id: 3, event_id: 15, role: 'user')
Attendee.create(user_id: 4, event_id: 15, role: 'user')
Attendee.create(user_id: 5, event_id: 15, role: 'user')
Attendee.create(user_id: 6, event_id: 15, role: 'user')
Attendee.create(user_id: 7, event_id: 15, role: 'user')
Attendee.create(user_id: 8, event_id: 15, role: 'user')
Attendee.create(user_id: 9, event_id: 15, role: 'user')
Attendee.create(user_id: 10, event_id: 15, role: 'user')
Attendee.create(user_id: 11, event_id: 15, role: 'user')
Attendee.create(user_id: 12, event_id: 15, role: 'user')
Attendee.create(user_id: 13, event_id: 15, role: 'user')
Attendee.create(user_id: 14, event_id: 15, role: 'user')
Attendee.create(user_id: 15, event_id: 15, role: 'speaker')
Attendee.create(user_id: 16, event_id: 15, role: 'user')
Attendee.create(user_id: 1, event_id: 16, role: 'user')
Attendee.create(user_id: 2, event_id: 16, role: 'user')
Attendee.create(user_id: 3, event_id: 16, role: 'user')
Attendee.create(user_id: 4, event_id: 16, role: 'user')
Attendee.create(user_id: 5, event_id: 16, role: 'user')
Attendee.create(user_id: 6, event_id: 16, role: 'user')
Attendee.create(user_id: 7, event_id: 16, role: 'user')
Attendee.create(user_id: 8, event_id: 16, role: 'user')
Attendee.create(user_id: 9, event_id: 16, role: 'user')
Attendee.create(user_id: 10, event_id: 16, role: 'user')
Attendee.create(user_id: 11, event_id: 16, role: 'user')
Attendee.create(user_id: 12, event_id: 16, role: 'user')
Attendee.create(user_id: 13, event_id: 16, role: 'user')
Attendee.create(user_id: 14, event_id: 16, role: 'user')
Attendee.create(user_id: 15, event_id: 16, role: 'user')
Attendee.create(user_id: 16, event_id: 16, role: 'speaker')



